### ISSUE TITLE
The attribute assigned in constructor appears more than once

### ISSUE THREAD

**Issue by doyou89** [lucsorel/py2puml#22]
When an attribute is assigned more than once in class constructor
```python
class DupAttr:
    def __init__(self, name=None):
        self.name = name
        if not self.name:
            self.name = ''
```

The attribute(here "name") appears several times.
```plantuml
@startuml
class umlclass.DupAttr {
  name: None
  name: None
}
@enduml
```

**Comment by lucsorel** [comment]
hi @doyou89, thank you for reporting your use case.

It is a known behavior of py2puml: see #20 where another user suggested similar cases. The issues here are:
- there is no simple solution to document a constructor a code which assigns different values (specially when the type annotations differ) to the same attribute (see the use-cases exposed in issue #20). Should the first detected assignment take precedence or the last one?
- there are some workaround (and best practices) to solve what seems to be a 'code smell' _- a hint that the codebase seems to have a design issue -_ (if you can change the codebase):
  - a constructor should not handle business logic, this should go in a factory (a static method or an independent function)
  - the logic could stay in the constructor and a value assigned to a local variable, then assign the local variable to the attribute

I know that these answers may not be fully satisfying and I am open to suggestions if you come up with other ways to solve this problem. What approach would you recommend?

**Comment by doyou89** [comment]
I understand you. I also think it's better to modify the code.
Thank your explanation. :smile:
