### ISSUE TITLE
`ModuleNotFoundError` when library folder uses a library folder on the same level

### ISSUE THREAD

**Issue by mikeweltevrede** [lucsorel/py2puml#23]
Hi,

I have following file structure:
```
project/
└── my_model/
    ├── __init__.py
    ├── module_model_main.py
    ├── module_model_1.py
    └── etcetera
└── template/
    └── utility/
        ├── __init__.py
        ├── module_utility_1.py
        └── etcetera
    ├── __init__.py
    ├── module_template_1.py
    └── etcetera
├── __init__.py
└── etcetera
```

`my_model/module_model_main.py` imports modules from:
* `template/module_template_1.py` (and `etcetera`)
* `template/utility/module_utility_1.py` (and `etcetera`)
* `my_model/module_model_1.py` (and `etcetera`)

where the latter imports from `template/module_template_1.py` (and `etcetera`) as well.

When running the code at the bottom of this post (from the `project/` folder), I get a specific `ModuleNotFoundError`:
```
File "[...]\my_model\module_model_main.py", line 17, in <module>
    from my_model.module_model_1 import ClassModel1
  File "[...]\my_model\module_model_1.py", line 1, in <module>        
    from template.module_template_1 import ClassTemplate1
  File "[...]\template\module_template_1.py", line 9, in <module>
    from utility.module_utility_1 import function_utility
ModuleNotFoundError: No module named 'utility'
```

At the highest execution level in `my_model/module_model_main.py` where the error also occurs, `py2puml` already succeeded past the following imports:
```
from template.module_template_1 import ClassTemplate1
from template.module_template_2 import ClassTemplate2
from template.module_template_3 import ClassTemplate3
from template.module_template_4 import ClassTemplate4
from template.module_template_5 import ClassTemplate5
from template.utility.module_utility_1 import ClassUtility1
```

As such, it errors on `from my_model.module_model_1 import ClassModel1`. How can it be that `py2puml` recognized `template.utility` with the explicit imports but not within this line? Can it be because it is on the same level? Is there a solution?

----------------

Executed code:
```
from py2puml.py2puml import py2puml
import findspark

findspark.init()  # Needed to allow finding pyspark as a module

print(''.join(
    py2puml('my_model/', 'my_model')
))
```

**Comment by lucsorel** [comment]
I think the problem lies in this import:
```text
File "[...]\template\module_template_1.py", line 9, in <module>
    from utility.module_utility_1 import function_utility
```
Shouldn't the module path be `template.utility.module_utility_1` instead of `utility.module_utility_1`?

**Comment by mikeweltevrede** [comment]
Indeed, that was an error. My apologies for overseeing this and thank you for the quick response :)
