### ISSUE TITLE
ValueError raised when compound types have digits

### ISSUE THREAD

**Issue by anaellorimier** [lucsorel/py2puml#35]
Hey,

Here's a simple example that yield a ValueError:
```python
class int64:
    def __init__(self, value: int) -> None:
        self.value: int = value

class Main:
    def __init__(self):
        self.a: list[int64] = [int64(0)] * 5
```
```bash
ValueError: list[int64] seems to be an invalid type annotation
```

I think fixing it is as simple as adding `0-9` in the compiled regex

Kinda critical for applications using numpy, as numpy types usually contain digits (i.e: `numpy.typing.NDArray[numpy.float64]`)

**Comment by lucsorel** [comment]
:pray: thank you  @anaellorimier for reporting the bug.

I fixed it in pull request https://github.com/lucsorel/py2puml/pull/36. Would you have time to review it before I merge it, please?

**Comment by lucsorel** [comment]
@anaellorimier the fix is published to https://pypi.org/project/py2puml/. Use version 0.6.1 to handle class names with digits in it.

Thank you again for reporting the bug and for suggesting the way to solve it :pray:

**Comment by anaellorimier** [comment]
Thanks a lot for the quick fix ! This will help my team a lot.
