### ISSUE TITLE
Question: event handling/interactive usage of outputs

### ISSUE THREAD

**Issue by DoctorMG** [lucsorel/py2puml#44]
I look for some interactive way to create such diagrams (with context menu options on nodes, drag / drop) etc.
So I need events to handle commands.
Is it possible/intended to generate such event handlers on the py2uml outputs?

Thanks

**Comment by lucsorel** [comment]
hello @DoctorMG 

As far as I know, PlantUML is a syntax to create static diagrams (in png, pdf, svg formats, for example) out of a textual syntax. You could consider editing the svg diagrams to add some dynamicity but this is out of scope of the PlantUML syntax.

You can check if there are some PlantUML editors that offer a dynamic interface but I don't know any one that work this way. The idea of py2puml is to generate such diagrams by inspecting the codebase, not by interacting with a user, I am sorry.
