### ISSUE TITLE
detect instance variables in constructor

### ISSUE THREAD

**Issue by lucsorel** [lucsorel/py2puml#7]
The current approach detects class variables (which is how dataclass works). But non-dataclass classes should be handled as well.

**Comment by doyou89** [comment]
To detect instance variables, we should instantiate the class first.
Create the class with it's parameters as mock.
Initial parameters can be detected from __init__ using #3.

**Comment by lucsorel** [comment]
yes it is an approach that can be followed. The one I am following in my current work is to process the AST of the constructor and detect `self.x = x` assignment.

**Comment by MMartin09** [comment]
Sry but I don't understand what you mean. If I have a class

```
class Test:
  string_1: str = "String 1"
  string_2: str = "String 2"

  def __init__(self):
    pass
```

How can I create the correct UML?

**Comment by lucsorel** [comment]
in this case, the class test has 2 class attributes and no instance attribute. The value of `string_1` and `string_2` are shared for all instances of the Test class.

If you want instance attributes, the code should be:
```python
class Test:
  def __init__(self, string_1: str, string_2: str):
    self.string_1 = string_1
    self.string_2 = string_2
```

And if you want instance attributes with default values:
```python
class Test:
  def __init__(self, string_1: str = 'String 1', string_2: str = 'String 2'):
    self.string_1 = string_1
    self.string_2 = string_2
```

When I started this library, it was mainly to create a class diagram of dataclasses. The @dataclass decorator actually use the definition of class attributes to generate a constructor with instance attributes (among other things). This issue aims at handling instance attributes defined in the constructor of a class which is not a dataclass.

**Comment by MMartin09** [comment]
Okay, I understand. But I think this could be a really great tool.

**Comment by doyou89** [comment]
Followings are the code that gets instance variables from the class definition code.
This may be helpful for this issue.
```python
class Address(object):
    street: str
    zipcode: str
    city: str

class Worker:
    name: str
    # forward refs are skipped for now
    colleagues: List['Worker']

    def __init__(self):
        self.addr: Address
        self.address: Address = Address()
        self.old_addr = Address()
        self.cons = []
        self.cons[0] = 0
        self.age = self.max_age = 0
        flag = 0
        self.age += 1
        addr = Address()
    
    def func(self, age):
        self.your_age = age
        return self.age
"""

import ast
import pprint
p=ast.parse(code)
for cls in p.body:
    if isinstance(cls, ast.ClassDef):
        print(cls.name)
        for m in cls.body:
            if isinstance(m, ast.FunctionDef):
                print(m.name)
                for a in m.body:
                    if isinstance(a, ast.AnnAssign):
                        if isinstance(a.target, ast.Attribute):
                            if a.target.value.id == 'self':
                                print(f'{a.target.value.id}.{a.target.attr}: {a.annotation.id}')
                    elif isinstance(a, ast.AugAssign):
                        pass
                    elif isinstance(a, ast.Assign):
                        for t in a.targets:
                            if isinstance(t, ast.Attribute):
                                if t.value.id == 'self':
                                    print(f'{t.value.id}.{t.attr}')
```
This will generate output:
```
Address
Worker
__init__
self.addr: Address
self.address: Address
self.old_addr
self.cons
self.age
self.max_age
func
self.your_age
```

**Comment by lucsorel** [comment]
hi @doyou89 :smiley: 

Thank you for your suggestion. I am coming up with some similar code, but following the visitor pattern so that:

* the underlying code does not rely on the code structure: the `self.x = ...` assignments could be within several layers of `if` conditions
* it can handle different assignment spellings (`self.x = x`, `self.x, self.y = x, y`, etc.)

Thank you for pointing out some cases like `self.cons[0] = 0`.
